"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.clockRouter = void 0;
const express_1 = require("express");
const controller_1 = require("./controller");
exports.clockRouter = (0, express_1.Router)();
exports.clockRouter.get('/', controller_1.clockController.get);
exports.clockRouter.post('/set', controller_1.clockController.set);
exports.clockRouter.post('/pause', controller_1.clockController.pause);
exports.clockRouter.post('/clear', controller_1.clockController.clear);
