"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.clubRouter = void 0;
const express_1 = require("express");
const controller_1 = require("./controller");
exports.clubRouter = (0, express_1.Router)();
exports.clubRouter.get('/', controller_1.clubController.getClubs);
exports.clubRouter.get('/:id', controller_1.clubController.getClub);
exports.clubRouter.post('/', controller_1.clubController.createClub);
exports.clubRouter.patch('/:id', controller_1.clubController.updateClub);
exports.clubRouter.delete('/:id', controller_1.clubController.deleteClub);
