import { Request, Response } from 'express'

export const archeryController = {
  getMatch: async (req: Request, res: Response) => {
    res.json([
      {
        category: 'U14 - Эрэгтэйчүүдийн ганцаарчилсан',
        name: 'Б. Балданбаатар',
        arrow1: 10,
        arrow2: 9,
        arrow3: 8,
        arrow4: 7,
        arrow5: 6,
        arrow6: 5,
        total: 45,
        set: 1,
      },
      {
        category: 'U14 - Эрэгтэйчүүдийн ганцаарчилсан',
        name: 'Б. Бадамсэрэжид',
        arrow1: 5,
        arrow2: 6,
        arrow3: 7,
        arrow4: 8,
        arrow5: 9,
        arrow6: 10,
        total: 45,
        set: 2,
      },
    ])
  },
  getBracket: async (req: Request, res: Response) => {
    res.json([
      {
        category: 'U14 - Эрэгтэйчүүдийн ганцаарчилсан',
        first: 'AAAAAAAAAAAAAAAA',
        second: 'BBBBBBBBBBBBBBBB',
        third: 'CCCCCCCCCCCCCCCC',
        firstScore: 100,
        secondScore: 90,
        thirdScore: 80,
      },
      {
        category: 'U14 - Эрэгтэйчүүдийн ганцаарчилсан',
        first: 'DDDDDDDDDDDDDDDD',
        second: 'EEEEEEEEEEEEEEEE',
        third: 'FFFFFFFFFFFFFFFF',
        firstScore: 70,
        secondScore: 60,
        thirdScore: 50,
      },
      {
        category: 'U14 - Эрэгтэйчүүдийн ганцаарчилсан',
        first: 'GGGGGGGGGGGGGGGG',
        second: 'HHHHHHHHHHHHHHHH',
        third: 'IIIIIIIIIIIIIIII',
        firstScore: 40,
        secondScore: 30,
        thirdScore: 20,
      },
      {
        category: 'U14 - Эрэгтэйчүүдийн ганцаарчилсан',
        first: 'KKKKKKKKKKKKKKKK',
        second: 'LLLLLLLLLLLLLLLL',
        third: 'MMMMMMMMMMMMMMMM',
        firstScore: 30,
        secondScore: 20,
        thirdScore: 10,
      },
      {
        category: 'U14 - Эрэгтэйчүүдийн ганцаарчилсан',
        first: 'NNNNNNNNNNNNNNNN',
        second: '',
        third: '',
        firstScore: 20,
        secondScore: 10,
        thirdScore: '',
      },
      {
        category: 'U14 - Эрэгтэйчүүдийн ганцаарчилсан',
        first: 'QQQQQQQQQQQQQQQQ',
        second: '',
        third: '',
        firstScore: 10,
        secondScore: 0,
        thirdScore: '',
      },
      {
        category: 'U14 - Эрэгтэйчүүдийн ганцаарчилсан',
        first: 'TTTTTTTTTTTTTTTT',
        second: '',
        third: '',
        firstScore: 100,
        secondScore: 90,
        thirdScore: '',
      },
      {
        category: 'U14 - Эрэгтэйчүүдийн ганцаарчилсан',
        first: 'VVVVVVVVVVVVVVVV',
        second: '',
        third: '',
        firstScore: 100,
        secondScore: 90,
        thirdScore: '',
      },
    ])
  },
  getRanking: async (req: Request, res: Response) => {
    res.json([
      {
        name: 'Бүдүүн Билгүүдэй',
        category: 'U14 - Эрэгтэйчүүдийн ганцаарчилсан',
        first: 1,
        second: 2,
        total: 3,
        rank: 1,
      },
      {
        name: 'BBBBBBBBBBBBBBBB',
        category: 'U14 - Эрэгтэйчүүдийн ганцаарчилсан',
        first: 4,
        second: 5,
        total: 6,
        rank: 2,
      },
      {
        name: 'CCCCCCCCCCCCCCCC',
        category: 'U14 - Эрэгтэйчүүдийн ганцаарчилсан',
        first: 7,
        second: 8,
        total: 9,
        rank: 3,
      },
      {
        name: 'EEEEEEEEEEEEEEEE',
        category: 'U14 - Эрэгтэйчүүдийн ганцаарчилсан',
        first: 10,
        second: 11,
        total: 12,
        rank: 4,
      },
      {
        name: 'FFFFFFFFFFFFFFFF',
        category: 'U14 - Эрэгтэйчүүдийн ганцаарчилсан',
        first: 13,
        second: 14,
        total: 15,
        rank: 5,
      },
      {
        name: 'GGGGGGGGGGGGGGGG',
        category: 'U14 - Эрэгтэйчүүдийн ганцаарчилсан',
        first: 16,
        second: 17,
        total: 18,
        rank: 6,
      },
      {
        name: 'HHHHHHHHHHHHHHHH',
        category: 'U14 - Эрэгтэйчүүдийн ганцаарчилсан',
        first: 19,
        second: 20,
        total: 21,
        rank: 7,
      },
      {
        name: 'IIIIIIIIIIIIIIII',
        category: 'U14 - Эрэгтэйчүүдийн ганцаарчилсан',
        first: 22,
        second: 23,
        total: 24,
        rank: 8,
      },
    ])
  },
}
